### PR TITLE
Add support for attachment questions

### PR DESCRIPTION
**Pull request by fjwong**
* Adds support for `type: "attachment"` questions.
* Implementation currently just opens a `file_selector` in all platforms.
  * Ideally this would also allow taking pictures/videos directly from camera on mobile, but this probably should come on a future PR.
* Validates `maxSize` and `mimeType` FHIR extensions if present.
  * Adds validation messages for both cases, although these are lacking translation on all languages.
* The attachment is added to the QuestionnaireResponse as data in base64.

### CODE REVIEW

**Comment by hanny-ph** [comment]
Tested on my side, please check the video below:

https://github.com/sujrd/faiadashu/assets/20153323/235e1f49-8fda-415c-84b3-c1ba087578a5

Apparently, `file_selector` doesn't need any permission for iOS.
I thought it was using another API which usually needs permission to access the files.

Basically, the fix is converting MIME Types to Uniform Type Identifiers [here](https://github.com/sujrd/faiadashu/pull/14/commits/54888bfe3ed825258492e504d138836941bcff9d).

**Review by hanny-ph — APPROVED** [review]
LGTM, Thanks!

**Comment by fjwong** [comment]
@hanny-ph Thank you very much for the changes. I just added one minor correction for web from my side.

@ajsviado @RemyDupont Please let us know if this works on your side when you have some time.

**Comment by fjwong** [comment]
@RemyDupont Thanks for the assistance.

**Pull request merged**
