### PR TITLE
Fix Fhirpath calculated expressions not being updated properly after disabling/enabling items via enableWhen

### PR DESCRIPTION
**Pull request by fjwong**

### CODE REVIEW

**Comment by ajsviado** [comment]
It seems that the value is only updated when there is a succeeeding event. Also when clearing the cache the answers for the hidden questions are not cleared.

Scenario: 
 - Show hidden questions > Answer questions > Change answer to hide questions (score not updated until another event occurs) > Change answer to show hidden questions again (score is updated as if the questions were hidden)

https://github.com/sujrd/faiadashu/assets/1407531/e8af568d-c232-4df7-9cf2-2482c5fa1d45

**Comment by fjwong** [comment]
@ajsviado @hanny-ph If you don't mind, could you guys test this again on your side on both Android and iOS?

I think the last changes I made should fix the issues reported in https://github.com/sujrd/faiadashu/pull/44#issuecomment-1719361516, or at least it works on my side on both iOS and Android.

**Comment by hanny-ph** [comment]
> @ajsviado @hanny-ph If you don't mind, could you guys test this again on your side on both Android and iOS?
> 
> I think the last changes I made should fix the issues reported in [#44 (comment)](https://github.com/sujrd/faiadashu/pull/44#issuecomment-1719361516), or at least it works on my side on both iOS and Android.

I tested it on my side, and it does work as expected.

**Review by hanny-ph — APPROVED** [review]
LGTM, thank you for the changes.

**Comment by ajsviado** [comment]
I tested the sample app on for faiadashu and everything is working properly.

Unfortunately for the smart forms sdk sample android app the same problem still exists. Not sure if there is a problem with the way smart forms sdk integrates the faiadashu library. Will continue to investigate on the smart forms android side.

Approving this code change.

**Review by ajsviado — APPROVED** [review]

**Comment by fjwong** [comment]
> I tested the sample app on for faiadashu and everything is working properly.
> 
> Unfortunately for the smart forms sdk sample android app the same problem still exists. Not sure if there is a problem with the way smart forms sdk integrates the faiadashu library. Will continue to investigate on the smart forms android side.
> 
> Approving this code change.

@ajsviado I see. Thank you for the review. From my side, I compiled the sample app for android and ran it in the simulator and it worked correctly at least.

Let's try seeing this again together next week. I'll merge this in the meantime.

**Pull request merged**
