### PR TITLE
Release 0.11.0

### PR DESCRIPTION
**Pull request by hanny-ph**
Basically, this PR will be the initial release of `sujrd/faiadashu`.

This collection comprises all great developments by the team initiated at the point of forking from the primary repository.

Please check the updated changelog here: https://github.com/sujrd/faiadashu/pull/80/commits/4377f589644f8a3ce21e3627fdba1c197840bea7

### CODE REVIEW

**Comment by fjwong** [comment]
@hanny-ph Thank you for taking the time to do this. Just a few comments:

* Shouldn't we increase the `faiadashu` version to `0.11.0` in pubspec.yaml? Right now it's still in `0.8.0`.
* Maybe it'd be good to update the SDC capabilities document too. I've made a patch for this just in case: 
[0001-Update-SDC-capabilities-document.patch](https://github.com/sujrd/faiadashu/files/13278498/0001-Update-SDC-capabilities-document.patch)
  * Feel free to modify as needed.

**Comment by hanny-ph** [comment]
@fjwong Thank you so much for the patch.
I bumped the version of `faiadashu`, `faiabench`, and `faiadashu_online`.
As for `faiabench`, I made a major release since we are introducing breaking changes (fhir 0.11.0).

**Comment by fjwong** [comment]
@hanny-ph Thank you for the changes.
Just one more thing, if I run `flutter pub get` on the root folder with the current changes, I end up with changes in `example/pubspec.lock` due to the version bump.
Perhaps it'd be good to add this to the changes as well.

**Review by fjwong — APPROVED** [review]
@hanny-ph Thanks a lot for the changes.
I think this is looking pretty good from my side.

**Pull request merged**
