### PR TITLE
Bump dependencies to support Flutter 3.24.1

### PR DESCRIPTION
**Pull request by hanny-ph**
This PR bumps Flutter to the latest version.

### CODE REVIEW

**Review by fjwong — COMMENTED** [review]
@hanny-ph Thank you for the changes. I think the upgrade itself looks mostly fine. 

There's one minor detail though, which is that these changes include an update to the `simple_html_css` package. Apparently, on v5.0.0 they finally ended up removing automatic html unescaping (https://github.com/ali-thowfeek/simple_html_css_flutter/blob/main/CHANGELOG.md)

This is causing now text such as `Temperature < 37` to instead show as `Temperature &lt; 37` instead, for example.

Probably we may need to either modify or remove the changes we added in https://github.com/sujrd/faiadashu/blob/develop/lib/utils/to_text_span.dart I think

**Comment by hanny-ph** [comment]
> Probably we may need to either modify or remove the changes we added in https://github.com/sujrd/faiadashu/blob/develop/lib/utils/to_text_span.dart I think

Thanks for your review. I am more inclined to remove the changes, but I will test it first. 🙇

**Comment by hanny-ph** [comment]
@fjwong Tested on my side, and it works as expected.

**Input:**

Screenshot 2024-09-18 at 10 21 11

**Output:**

Screenshot 2024-09-18 at 10 18 57

**Review by fjwong — APPROVED** [review]
@hanny-ph Thank you for the changes. I think everything's in order. :)

**Pull request merged**
