### PR TITLE
Broadcast initial response

### PR DESCRIPTION
**Pull request by fjwong**

### CODE REVIEW

**Comment by hanny-ph** [comment]
Just dropping my thought here, actually, I'm more slightly inclined to have a different function, e.g. `onQuestionnaireInitialized()`. The only reason is to have a clear separation between on init and on questionnaire response change. But doing this will also be adding tasks for our side to handle this event. :D
___
Digging a bit deeper, I think the issue relies on `faiabench` not the library itself, so I'm fine with this change. Apparently, faiabench is trying to update the state when building the widget. (kinda well known issue)
```
ref.read(widget.fillerOutputProvider.notifier).updateFhirResource(resource);
```

**Review by hanny-ph — APPROVED** [review]
LGTM, thanks!

**Comment by fjwong** [comment]
> Just dropping my thought here, actually, I'm more slightly inclined to have a different function, e.g. `onQuestionnaireInitialized()`. The only reason is to have a clear separation between on init and on questionnaire response change. But doing this will also be adding tasks on our side to handle this event. 😆

That is valid point. I guess we can add it later and add support for it on our side as well.

> Digging a bit deeper, I think the issue relies on `faiabench` not the library itself, so I'm fine with this change. Apparently, faiabench is trying to update the state when building the widget. (kinda well-known issue)
> 
> ```
> ref.read(widget.fillerOutputProvider.notifier).updateFhirResource(resource);
> ```

That is true. I was also thinking about that earlier as well.

I think I'll rearrange things to call `_handleChangedQuestionnaireResponse` here and then execute the line in `faiabench` within a `Future` instead.

**Comment by fjwong** [comment]
@hanny-ph Thanks for the comments. I've made the changes I mentioned above.

The change is relatively minor, and I've tested on my side that it works. I'll go ahead and merge this I think, but please let me know if you find any issues related to these changes.

**Pull request merged**
